apiVersion: v1
kind: Secret
metadata:
  name: guacamole
  namespace: netboot-guacamole
type: Opaque
data:
  database: guacamole-db
  user_login: admin
  user_password: Integrity123
  root_password: Integrity123